use_frameworks!

target 'TipTextField_Example' do
  pod 'TipTextField', :path => '../'

  target 'TipTextField_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
